version: "3.8"
services:
  bookingsdb:
    image: mysql
    container_name: bookingsdb
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","bookingsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '3309:3306'

    environment:
#      MYSQL_USER: dockerbookingdb
#      MYSQL_PASSWORD: bookings
      MYSQL_ROOT_PASSWORD: bookings
      MYSQL_DATABASE: bookings

  paymentsdb:
    image: mysql
    container_name: paymentsdb
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","paymentsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '3308:3306'

    environment:
#      MYSQL_USER: dockerpaymentsdb
#      MYSQL_PASSWORD: asnpa 94
      MYSQL_ROOT_PASSWORD: payments
      MYSQL_DATABASE: payments

  movie-services-registry:
    image: movie-services-registry
    container_name: movie-services-registry
    build: ./movie-services-registry
    ports:
      - '8761:8761'

  booking-service:
    image: booking-service
    container_name: booking-service
    build: ./booking-service
    depends_on:
      bookingsdb:
        condition: service_healthy
#    ports:
#      - '9090:9090'
    environment:
      MYSQL_HOST: bookingsdb
      DB_NAME: bookings


  payment-service:
    image: payment-service
    container_name: payment-service
    build: ./payment-service
    depends_on:
      paymentsdb:
        condition: service_healthy
#    ports:
#      - '9091:9091'
    environment:
      MYSQL_HOST: paymentsdb
      DB_NAME: payments

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - '8765:8765'
