server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
          - Path=/bookings/**
          filters:
          - name: CircuitBreaker
            args:
              name: booking-route
              fallbackUri: forward:/booking-fallback
